name: flutter_tex_js
description: A lightweight TeX plugin that uses KaTeX (JavaScript) in a native web view to render to PNG
version: 1.2.1
homepage: https://github.com/amake/flutter_tex_js

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.12.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.10.0-nullsafety

flutter:
  plugin:
    platforms:
      android:
        package: com.madlonkay.flutter_tex_js
        pluginClass: FlutterTexJsPlugin
      ios:
        pluginClass: FlutterTexJsPlugin
      web:
        pluginClass: FlutterTexJsWeb
        fileName: flutter_tex_js_web.dart
