name: flutter_tex_js_android
description: Android implementation of the flutter_tex_js plugin.
version: 3.0.0
homepage: https://github.com/amake/flutter_tex_js

environment:
  sdk: '>=2.12.0 <4.0.0'
  flutter: '>=1.20.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_tex_js_platform_interface: ^1.0.0
  # flutter_tex_js_platform_interface:
  #   path: ../flutter_tex_js_platform_interface

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    implements: flutter_tex_js
    platforms:
      android:
        package: com.madlonkay.flutter_tex_js
        pluginClass: FlutterTexJsPlugin
        dartPluginClass: TexRendererAndroid
